name: Build Dev Version Extension

# on: [workflow_dispatch]
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Enable development framework scripts
        run: |
          sed -i "s/<!-- //" ${{ github.workspace }}/OooDev/META-INF/manifest.xml
          # cat ${{ github.workspace }}/OooDev/META-INF/manifest.xml
          # echo

      - name: Update version to development
        run: |
          sed -i '/<version value/ s/"\/>/-Dev"\/>/' ${{ github.workspace }}/OooDev/description.xml
          # cat ${{ github.workspace }}/OooDev/description.xml
          # echo
          
      - name: Zip repo
        # uses: papeloto/action-zip@v1
        uses: vimtor/action-zip@v1
        with:
          files: OooDev/
          # recursive: false
          dest: OooDev-dev.oxt
          
      - uses: actions/upload-artifact@v1
        with:
         name: OooDev-dev.oxt
         path: ${{ github.workspace }}/OooDev-dev.oxt
